stages:
  - build

docker-build-prod:
  stage: build
  tags:
    - docker
  script:
    - if [ "${CI_COMMIT_REF_NAME:0:1}" = "v" ]; then /bin/sh -c "curl -X POST -F token=$CI_TOKEN -F ref=$CI_BRANCH -F variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME -F variables[UPSTREAM_PATH]=$CI_PROJECT_PATH -F variables[UPSTREAM_IMAGE]=paydia/merchant-saldo:$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_ID/trigger/pipeline"; fi
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
